# Generated by Django 4.0.2 on 2022-03-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommendFor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
