# Generated by Django 4.0.2 on 2022-03-05 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Homestay', 'Homestay'), ('Villa', 'Villa'), ('Hotel', 'Hotel')], max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('total_rooms', models.IntegerField()),
                ('price_per_room', models.IntegerField()),
                ('person_per_room', models.IntegerField()),
                ('increase_price_per_person', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('complementary_breakfast', models.BooleanField(default=False)),
                ('luxirous_room', models.BooleanField(default=False)),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('hot_shower', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('smoking_drinking', models.BooleanField(default=False)),
                ('receive_facility', models.BooleanField(default=False)),
                ('drop_facility', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('nearest_landmark', models.CharField(max_length=255)),
                ('rules', models.TextField()),
                ('main_image', models.ImageField(upload_to='property/main_image')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/other_images')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
